# Generated by Django 5.0.3 on 2024-05-09 04:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên sự kiện')),
                ('start_date', models.DateField(verbose_name='Ngày tổ chức')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='Thời hạn (ngày)')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mô tả')),
                ('hours', models.IntegerField(verbose_name='Số giờ tình nguyện')),
                ('likes', models.IntegerField(default=0, verbose_name='Lượt yêu thích')),
                ('comments', models.IntegerField(default=0, verbose_name='Bình luận')),
                ('shares', models.IntegerField(default=0, verbose_name='Lượt chia sẻ')),
                ('participants', models.IntegerField(default=0, verbose_name='Số người tham gia')),
            ],
            options={
                'verbose_name': 'Sự kiện tình nguyện',
                'verbose_name_plural': 'Sự kiện tình nguyện',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'Tên đăng nhập đã tồn tại.'}, help_text='Yêu cầu 30 ký tự hoặc ít hơn. Chỉ chứa chữ cái, số và các ký tự @/./+/-/_', max_length=30, unique=True, verbose_name='username')),
                ('is_superuser', models.BooleanField(default=False, help_text='Chỉ định người dùng có tất cả các quyền quản trị hệ thống.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Chỉ định người dùng có quyền truy cập vào trang quản trị (admin).', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định người dùng được coi là "active". Hủy chọn để vô hiệu hóa tài khoản này.', verbose_name='active')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('name', models.CharField(max_length=30, verbose_name='Tên')),
                ('age', models.IntegerField(verbose_name='Tuổi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
                ('skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kỹ năng')),
                ('hours_worked', models.IntegerField(default=0, verbose_name='Số giờ tình nguyện')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('events_attended', models.ManyToManyField(blank=True, related_name='attendees', to='volunteer_management_app.volunteereventpost', verbose_name='Sự kiện đã tham gia')),
                ('liked_events', models.ManyToManyField(blank=True, related_name='liked_users', to='volunteer_management_app.volunteereventpost', verbose_name='Sự kiện yêu thích')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['username'],
            },
        ),
    ]
