# Generated by Django 5.0.3 on 2024-05-09 12:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'Tên đăng nhập đã tồn tại.'}, help_text='Yêu cầu 30 ký tự hoặc ít hơn. Chỉ chứa chữ cái, số và các ký tự @/./+/-/_', max_length=30, unique=True, verbose_name='username')),
                ('is_superuser', models.BooleanField(default=False, help_text='Chỉ định người dùng có tất cả các quyền quản trị hệ thống.', verbose_name='Quản trị hệ thống')),
                ('is_staff', models.BooleanField(default=False, help_text='Chỉ định người dùng có quyền truy cập vào trang quản trị (admin).', verbose_name='Nhân viên hệ thống')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định người dùng được coi là "active". Hủy chọn để vô hiệu hóa tài khoản này.', verbose_name='Trạng thái hoạt động')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('name', models.CharField(max_length=30, verbose_name='Tên')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Tuổi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
                ('skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kỹ năng')),
                ('hours_worked', models.IntegerField(default=0, verbose_name='Số giờ tình nguyện')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Người dùng quản trị',
                'verbose_name_plural': 'Người dùng quản trị',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('volunteer_management_app.customuser',),
        ),
        migrations.CreateModel(
            name='VolunteerEventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên sự kiện')),
                ('start_date', models.DateTimeField(verbose_name='Ngày tổ chức')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Mô tả chi tiết về sự kiện, đây cũng sẽ là nội dụng  cho bài viết về sự kiện tình nguyện này.', verbose_name='Mô tả sự kiện')),
                ('hours', models.IntegerField(default=1, help_text='Số giờ tối thiểu mà người tham gia cần tình nguyện.', verbose_name='Số giờ tình nguyện')),
                ('likes', models.IntegerField(default=0, editable=False, verbose_name='Lượt yêu thích')),
                ('shares', models.IntegerField(default=0, editable=False, verbose_name='Lượt chia sẻ')),
                ('max_participants', models.IntegerField(default=10, verbose_name='Số người tham gia tối đa')),
                ('current_participants', models.IntegerField(default=0, editable=False, verbose_name='Số người tham gia hiện tại')),
                ('status', models.CharField(choices=[('planned', 'Đang lên kế hoạch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã kết thúc')], default='planned', max_length=20, verbose_name='Trạng thái')),
                ('organizer', models.ForeignKey(help_text='Chỉ người dùng quản trị mới có thể tổ chức sự kiện.', on_delete=django.db.models.deletion.CASCADE, related_name='events_organized', to=settings.AUTH_USER_MODEL, verbose_name='Người tổ chức')),
            ],
            options={
                'verbose_name': 'Sự kiện tình nguyện',
                'verbose_name_plural': 'Sự kiện tình nguyện',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Ngày báo cáo')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Số người tham gia')),
                ('report_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Nội dung báo cáo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
                ('event', models.ForeignKey(help_text='Chỉ có thể báo cáo những sự kiện đã kết thúc mà đã bạn tổ chức.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='volunteer_management_app.volunteereventpost', verbose_name='Sự kiện')),
            ],
            options={
                'verbose_name': 'Báo cáo sự kiện',
                'verbose_name_plural': 'Báo cáo sự kiện',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='events_attended',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='volunteer_management_app.volunteereventpost', verbose_name='Sự kiện đã tham gia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_events',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='volunteer_management_app.volunteereventpost', verbose_name='Sự kiện yêu thích'),
        ),
    ]
