# Generated by Django 5.0.3 on 2024-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteereventpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='volunteereventpost',
            name='status',
            field=models.CharField(choices=[('planned', 'Đang lên kế hoạch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã kết thúc')], default='planned', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='volunteereventpost',
            name='likes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Lượt yêu thích'),
        ),
        migrations.AlterField(
            model_name='volunteereventpost',
            name='shares',
            field=models.IntegerField(default=0, editable=False, verbose_name='Lượt chia sẻ'),
        ),
    ]
