# Generated by Django 5.0.3 on 2024-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteereventpost',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Tên sự kiện'),
        ),
    ]
